<a href="https://colab.research.google.com/github/ancestor9/2025_Winter_Deep-Learning-with-TensorFlow/blob/main/20260114_04_pytorch/code_part1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<table style="width:100%">
<tr>
<td style="vertical-align:middle; text-align:left;">
<font size="2">
Supplementary code for the <a href="http://mng.bz/orYv">Build a Large Language Model From Scratch</a> book by <a href="https://sebastianraschka.com">Sebastian Raschka</a><br>
<br>Code repository: <a href="https://github.com/rasbt/LLMs-from-scratch">https://github.com/rasbt/LLMs-from-scratch</a>
</font>
</td>
<td style="vertical-align:middle; text-align:left;">
<a href="http://mng.bz/orYv"><img src="https://sebastianraschka.com/images/LLMs-from-scratch-images/cover-small.webp" width="100px"></a>
</td>
</tr>
</table>


# Appendix A: Introduction to PyTorch (Part 1)

## A.1 What is PyTorch

In [1]:
import torch

print(torch.__version__)

2.9.0+cu126


In [2]:
print(torch.cuda.is_available())

True


<img src="https://sebastianraschka.com/images/LLMs-from-scratch-images/appendix-a_compressed/1.webp" width="400px">

<img src="https://sebastianraschka.com/images/LLMs-from-scratch-images/appendix-a_compressed/2.webp" width="300px">

<img src="https://sebastianraschka.com/images/LLMs-from-scratch-images/appendix-a_compressed/3.webp" width="300px">

<img src="https://sebastianraschka.com/images/LLMs-from-scratch-images/appendix-a_compressed/4.webp" width="500px">

<img src="https://sebastianraschka.com/images/LLMs-from-scratch-images/appendix-a_compressed/5.webp" width="500px">

## A.2 Understanding tensors

<img src="https://sebastianraschka.com/images/LLMs-from-scratch-images/appendix-a_compressed/6.webp" width="400px">

### A.2.1 Scalars, vectors, matrices, and tensors

In [7]:
import torch
import numpy as np

# create a 0D tensor (scalar) from a Python integer
tensor0d = torch.tensor(1)

# create a 1D tensor (vector) from a Python list
tensor1d = torch.tensor([1, 2, 3])

# create a 2D tensor from a nested Python list
tensor2d = torch.tensor([[1, 2],
                         [3, 4]])

# create a 3D tensor from a nested Python list
tensor3d_1 = torch.tensor([[[1, 2], [3, 4]],
                           [[5, 6], [7, 8]]])

In [ ]:
# create a 3D tensor from NumPy array
ary3d = np.array([[[1, 2], [3, 4]],
                  [[5, 6], [7, 8]]])
tensor3d_2 = torch.tensor(ary3d)  # Copies NumPy array
tensor3d_3 = torch.from_numpy(ary3d)  # Shares memory with NumPy array

In [12]:
ary3d[0, 0, 0] = 999
print(tensor3d_2) # remains unchanged

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])


In [13]:
print(tensor3d_3) # changes because of memory sharing

tensor([[[999,   2],
         [  3,   4]],

        [[  5,   6],
         [  7,   8]]])


### A.2.2 Tensor data types

In [14]:
tensor1d = torch.tensor([1, 2, 3])
print(tensor1d.dtype)

torch.int64


In [15]:
floatvec = torch.tensor([1.0, 2.0, 3.0])
print(floatvec.dtype)

torch.float32


In [16]:
floatvec = tensor1d.to(torch.float32)
print(floatvec.dtype)

torch.float32


### A.2.3 Common PyTorch tensor operations

In [17]:
tensor2d = torch.tensor([[1, 2, 3],
                         [4, 5, 6]])
tensor2d

tensor([[1, 2, 3],
        [4, 5, 6]])

In [18]:
tensor2d.shape

torch.Size([2, 3])

In [19]:
tensor2d.reshape(3, 2)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [20]:
tensor2d.view(3, 2)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [21]:
tensor2d.T

tensor([[1, 4],
        [2, 5],
        [3, 6]])

In [22]:
tensor2d.matmul(tensor2d.T)

tensor([[14, 32],
        [32, 77]])

In [23]:
tensor2d @ tensor2d.T

tensor([[14, 32],
        [32, 77]])

### **1. 분산과 상관관계 구하기 (내적으로)**

#### 1.1. 분산

In [41]:
import torch

# 1. 데이터 생성 (이미지 코드 참고)
tensor_rand_1 = torch.randint(low=10, high=100, size=(20,)).float()

# 2. Mean Centering (평균 빼기)
# 평균을 빼줌으로써 데이터를 '원점' 중심으로 이동시킵니다.
mean_1 = torch.mean(tensor_rand_1)
centered_1 = tensor_rand_1 - mean_1

# 3. 내적(Dot Product) 계산
# 자기 자신과 내적을 구합니다 (각 요소의 제곱의 합과 동일)
dot_self = torch.dot(centered_1, centered_1)

# 4. 분산(Variance) 도출
# 내적 결과를 (n-1)로 나누면 표본분산이 됩니다.
variance_by_dot = dot_self / (len(tensor_rand_1) - 1)

# 5. PyTorch 내장 함수와 비교
pytorch_variance = torch.var(tensor_rand_1)

print(f"내적을 이용한 분산: {variance_by_dot.item():.4f}")
print(f"PyTorch 내장 함수 분산: {pytorch_variance.item():.4f}")

내적을 이용한 분산: 727.7343
PyTorch 내장 함수 분산: 727.7342


### 1.2. 상관관계

In [48]:
import torch

# 1. 데이터 준비 (앞선 예시와 동일)
# float() 변환이 반드시 필요합니다.
x = tensor_rand_1.float()
y = tensor_rand_2.float()
n = x.size(0) # 데이터 개수 (20개)

# 2. Mean Centering (평균 빼기)
x_centered = x - torch.mean(x)
y_centered = y - torch.mean(y)

# 3. 공분산(Covariance) 계산
# 내적(Dot Product)을 (n-1)로 나누면 공분산입니다.
dot_xy = torch.dot(x_centered, y_centered)
covariance_custom = dot_xy / (n - 1)

# 4. 상관계수(Correlation) 계산
# 방법 A: 공분산을 각 표준편차의 곱으로 나눔
std_x = torch.std(x)
std_y = torch.std(y)
correlation_custom = covariance_custom / (std_x * std_y)

# 방법 B: 코사인 유사도 공식 활용 (두 Centered 벡터 사이의 각도)
# r = (A · B) / (||A|| * ||B||)
correlation_cosine = dot_xy / (torch.norm(x_centered) * torch.norm(y_centered))

# 5. 검증 (PyTorch 내장 함수와 비교)
actual_cov = torch.cov(torch.stack([x, y]))[0, 1]
actual_corr = torch.corrcoef(torch.stack([x, y]))[0, 1]

print(f"--- 직접 계산한 결과 ---")
print(f"내적 기반 공분산: {covariance_custom.item():.4f}")
print(f"내적 기반 상관계수: {correlation_custom.item():.4f}")
print(f"코사인 기반 상관계수: {correlation_cosine.item():.4f}")
print(f"\n--- PyTorch 내장 함수 결과 ---")
print(f"실제 공분산: {actual_cov.item():.4f}")
print(f"실제 상관계수: {actual_corr.item():.4f}")

--- 직접 계산한 결과 ---
내적 기반 공분산: -336843.9062
내적 기반 상관계수: -0.3875
코사인 기반 상관계수: -0.3875

--- PyTorch 내장 함수 결과 ---
실제 공분산: -336843.9062
실제 상관계수: -0.3875


| 개념 | 공식적 정의 | 내적(Dot Product)과의 관계 | 의미 |
|---|---|---|---|
| 내적 (Dot Product) | $\sum x_i y_i = X \cdot Y$ | 두 벡터의 기본 내적 | 두 벡터가 얼마나 같은 방향을 향하는가 |
| 공분산 (Covariance) | $\dfrac{1}{n-1}\sum (x_i - \bar{x})(y_i - \bar{y})$ | $\dfrac{1}{n-1}\,\langle \tilde{X}, \tilde{Y} \rangle$ | 두 변수가 함께 변하는 정도 (단위에 영향 받음) |
| 상관계수 (Correlation) | $\dfrac{\mathrm{Cov}(X,Y)}{\sigma_X \sigma_Y}$ | $\dfrac{\langle \tilde{X}, \tilde{Y} \rangle}{\|\tilde{X}\|\,\|\tilde{Y}\|} = \cos(\theta)$ | 공분산을 표준화한 값 (−1 ~ 1, 단위 무관) |


- 기하학적 해석: "상관계수는 코사인($\cos$) 값이다"데이터를 벡터로 보았을 때, 상관관계는 두 벡터 사이의 **각도($\theta$)**로 해석할 수 있습니다.

> 내적 > 0 (예각): 두 데이터가 비슷한 방향으로 움직입니다. (양의 상관관계)

> 내적 = 0 (직교): 두 데이터는 서로 아무런 선형적 관련이 없습니다. (상관관계 0)

> 내적 < 0 (둔각): 한 데이터가 커질 때 다른 데이터는 작아집니다. (음의 상관관계)


## A.3 Seeing models as computation graphs

<img src="https://sebastianraschka.com/images/LLMs-from-scratch-images/appendix-a_compressed/7.webp" width="600px">

In [49]:
import torch.nn.functional as F

y = torch.tensor([1.0])  # true label
x1 = torch.tensor([1.1]) # input feature
w1 = torch.tensor([2.2]) # weight parameter
b = torch.tensor([0.0])  # bias unit

z = x1 * w1 + b          # net input
a = torch.sigmoid(z)     # activation & output

loss = F.binary_cross_entropy(a, y)
print(loss)

tensor(0.0852)


## A.4 Automatic differentiation made easy

<img src="https://sebastianraschka.com/images/LLMs-from-scratch-images/appendix-a_compressed/8.webp" width="600px">

In [50]:
import torch.nn.functional as F
from torch.autograd import grad

y = torch.tensor([1.0])
x1 = torch.tensor([1.1])
w1 = torch.tensor([2.2], requires_grad=True)
b = torch.tensor([0.0], requires_grad=True)

z = x1 * w1 + b
a = torch.sigmoid(z)

loss = F.binary_cross_entropy(a, y)

grad_L_w1 = grad(loss, w1, retain_graph=True)
grad_L_b = grad(loss, b, retain_graph=True)

print(grad_L_w1)
print(grad_L_b)

(tensor([-0.0898]),)
(tensor([-0.0817]),)


In [ ]:
loss.backward()

print(w1.grad)
print(b.grad)

tensor([-0.0898])
tensor([-0.0817])


## A.5 Implementing multilayer neural networks

<img src="https://sebastianraschka.com/images/LLMs-from-scratch-images/appendix-a_compressed/9.webp" width="500px">

In [51]:
class NeuralNetwork(torch.nn.Module):
    def __init__(self, num_inputs, num_outputs):
        super().__init__()

        self.layers = torch.nn.Sequential(

            # 1st hidden layer
            torch.nn.Linear(num_inputs, 30),
            torch.nn.ReLU(),

            # 2nd hidden layer
            torch.nn.Linear(30, 20),
            torch.nn.ReLU(),

            # output layer
            torch.nn.Linear(20, num_outputs),
        )

    def forward(self, x):
        logits = self.layers(x)
        return logits

In [52]:
model = NeuralNetwork(50, 3)

In [53]:
print(model)

NeuralNetwork(
  (layers): Sequential(
    (0): Linear(in_features=50, out_features=30, bias=True)
    (1): ReLU()
    (2): Linear(in_features=30, out_features=20, bias=True)
    (3): ReLU()
    (4): Linear(in_features=20, out_features=3, bias=True)
  )
)


In [54]:
num_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
print("Total number of trainable model parameters:", num_params)

Total number of trainable model parameters: 2213


In [55]:
print(model.layers[0].weight)

Parameter containing:
tensor([[-0.1403,  0.1372,  0.0653,  ..., -0.0727,  0.0598, -0.1085],
        [ 0.0791, -0.0377, -0.1324,  ..., -0.0376, -0.0723, -0.0217],
        [-0.0861,  0.0746, -0.0914,  ...,  0.0225, -0.1101, -0.0745],
        ...,
        [ 0.0447,  0.1278,  0.0850,  ...,  0.1264,  0.1313,  0.0011],
        [-0.0036,  0.1191, -0.1253,  ...,  0.1400,  0.1144,  0.0227],
        [-0.0016,  0.1071, -0.0923,  ..., -0.0299, -0.0966,  0.0997]],
       requires_grad=True)


In [56]:
torch.manual_seed(123)

model = NeuralNetwork(50, 3)
print(model.layers[0].weight)

Parameter containing:
tensor([[-0.0577,  0.0047, -0.0702,  ...,  0.0222,  0.1260,  0.0865],
        [ 0.0502,  0.0307,  0.0333,  ...,  0.0951,  0.1134, -0.0297],
        [ 0.1077, -0.1108,  0.0122,  ...,  0.0108, -0.1049, -0.1063],
        ...,
        [-0.0787,  0.1259,  0.0803,  ...,  0.1218,  0.1303, -0.1351],
        [ 0.1359,  0.0175, -0.0673,  ...,  0.0674,  0.0676,  0.1058],
        [ 0.0790,  0.1343, -0.0293,  ...,  0.0344, -0.0971, -0.0509]],
       requires_grad=True)


In [57]:
print(model.layers[0].weight.shape)

torch.Size([30, 50])


In [58]:
torch.manual_seed(123)

X = torch.rand((1, 50))
out = model(X)
print(out)

tensor([[-0.1262,  0.1080, -0.1792]], grad_fn=<AddmmBackward0>)


In [59]:
with torch.no_grad():
    out = model(X)
print(out)

tensor([[-0.1262,  0.1080, -0.1792]])


In [60]:
with torch.no_grad():
    out = torch.softmax(model(X), dim=1)
print(out)

tensor([[0.3113, 0.3934, 0.2952]])


## A.6 Setting up efficient data loaders

<img src="https://sebastianraschka.com/images/LLMs-from-scratch-images/appendix-a_compressed/10.webp" width="600px">

In [61]:
X_train = torch.tensor([
    [-1.2, 3.1],
    [-0.9, 2.9],
    [-0.5, 2.6],
    [2.3, -1.1],
    [2.7, -1.5]
])

y_train = torch.tensor([0, 0, 0, 1, 1])

In [ ]:
X_test = torch.tensor([
    [-0.8, 2.8],
    [2.6, -1.6],
])

y_test = torch.tensor([0, 1])

In [ ]:
from torch.utils.data import Dataset


class ToyDataset(Dataset):
    def __init__(self, X, y):
        self.features = X
        self.labels = y

    def __getitem__(self, index):
        one_x = self.features[index]
        one_y = self.labels[index]
        return one_x, one_y

    def __len__(self):
        return self.labels.shape[0]

train_ds = ToyDataset(X_train, y_train)
test_ds = ToyDataset(X_test, y_test)

In [ ]:
len(train_ds)

5

In [ ]:
from torch.utils.data import DataLoader

torch.manual_seed(123)

train_loader = DataLoader(
    dataset=train_ds,
    batch_size=2,
    shuffle=True,
    num_workers=0
)

In [ ]:
test_ds = ToyDataset(X_test, y_test)

test_loader = DataLoader(
    dataset=test_ds,
    batch_size=2,
    shuffle=False,
    num_workers=0
)

In [ ]:
for idx, (x, y) in enumerate(train_loader):
    print(f"Batch {idx+1}:", x, y)

Batch 1: tensor([[ 2.3000, -1.1000],
        [-0.9000,  2.9000]]) tensor([1, 0])
Batch 2: tensor([[-1.2000,  3.1000],
        [-0.5000,  2.6000]]) tensor([0, 0])
Batch 3: tensor([[ 2.7000, -1.5000]]) tensor([1])


In [ ]:
train_loader = DataLoader(
    dataset=train_ds,
    batch_size=2,
    shuffle=True,
    num_workers=0,
    drop_last=True
)

In [ ]:
for idx, (x, y) in enumerate(train_loader):
    print(f"Batch {idx+1}:", x, y)

Batch 1: tensor([[-1.2000,  3.1000],
        [-0.5000,  2.6000]]) tensor([0, 0])
Batch 2: tensor([[ 2.3000, -1.1000],
        [-0.9000,  2.9000]]) tensor([1, 0])


<img src="https://sebastianraschka.com/images/LLMs-from-scratch-images/appendix-a_compressed/11.webp" width="600px">

## A.7 A typical training loop

In [ ]:
import torch.nn.functional as F


torch.manual_seed(123)
model = NeuralNetwork(num_inputs=2, num_outputs=2)
optimizer = torch.optim.SGD(model.parameters(), lr=0.5)

num_epochs = 3

for epoch in range(num_epochs):

    model.train()
    for batch_idx, (features, labels) in enumerate(train_loader):

        logits = model(features)

        loss = F.cross_entropy(logits, labels) # Loss function

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        ### LOGGING
        print(f"Epoch: {epoch+1:03d}/{num_epochs:03d}"
              f" | Batch {batch_idx:03d}/{len(train_loader):03d}"
              f" | Train/Val Loss: {loss:.2f}")

    model.eval()
    # Optional model evaluation

Epoch: 001/003 | Batch 000/002 | Train/Val Loss: 0.75
Epoch: 001/003 | Batch 001/002 | Train/Val Loss: 0.65
Epoch: 002/003 | Batch 000/002 | Train/Val Loss: 0.44
Epoch: 002/003 | Batch 001/002 | Train/Val Loss: 0.13
Epoch: 003/003 | Batch 000/002 | Train/Val Loss: 0.03
Epoch: 003/003 | Batch 001/002 | Train/Val Loss: 0.00


In [ ]:
model.eval()

with torch.no_grad():
    outputs = model(X_train)

print(outputs)

tensor([[ 2.8569, -4.1618],
        [ 2.5382, -3.7548],
        [ 2.0944, -3.1820],
        [-1.4814,  1.4816],
        [-1.7176,  1.7342]])


In [ ]:
torch.set_printoptions(sci_mode=False)
probas = torch.softmax(outputs, dim=1)
print(probas)

predictions = torch.argmax(probas, dim=1)
print(predictions)

tensor([[0.9991, 0.0009],
        [0.9982, 0.0018],
        [0.9949, 0.0051],
        [0.0491, 0.9509],
        [0.0307, 0.9693]])
tensor([0, 0, 0, 1, 1])


In [ ]:
predictions = torch.argmax(outputs, dim=1)
print(predictions)

tensor([0, 0, 0, 1, 1])


In [ ]:
predictions == y_train

tensor([True, True, True, True, True])

In [ ]:
torch.sum(predictions == y_train)

tensor(5)

In [ ]:
def compute_accuracy(model, dataloader):

    model = model.eval()
    correct = 0.0
    total_examples = 0

    for idx, (features, labels) in enumerate(dataloader):

        with torch.no_grad():
            logits = model(features)

        predictions = torch.argmax(logits, dim=1)
        compare = labels == predictions
        correct += torch.sum(compare)
        total_examples += len(compare)

    return (correct / total_examples).item()

In [ ]:
compute_accuracy(model, train_loader)

1.0

In [ ]:
compute_accuracy(model, test_loader)

1.0

## A.8 Saving and loading models

In [ ]:
torch.save(model.state_dict(), "model.pth")

In [ ]:
model = NeuralNetwork(2, 2) # needs to match the original model exactly
model.load_state_dict(torch.load("model.pth", weights_only=True))

<All keys matched successfully>

## A.9 Optimizing training performance with GPUs

### A.9.1 PyTorch computations on GPU devices

See [code-part2.ipynb](code-part2.ipynb)

### A.9.2 Single-GPU training

See [code-part2.ipynb](code-part2.ipynb)

### A.9.3 Training with multiple GPUs

See [DDP-script.py](DDP-script.py)